import type { AuditItem, SocialPage } from './types';

export const SAMPLE_PAGES: SocialPage[] = [
  { name: 'SAMARTH National Desk', url: 'https://instagram.com/samarthnational' },
  { name: 'UP Development Watch', url: 'https://facebook.com/updevelopmentwatch' },
  { name: 'Youth Connect India', url: 'https://youtube.com/@youthconnectindia' },
  { name: 'Policy Pulse', url: 'https://instagram.com/policypulse' },
  { name: 'Jan Samvad Live', url: 'https://facebook.com/jansamvadlive' },
  { name: 'Bharat Narrative Lab', url: 'https://youtube.com/@bharatnarrativelab' }
];

export const SAMPLE_AUDIT_ITEMS: AuditItem[] = [
  {
    id: 'sample-001',
    title: 'Metro extension explainer reel',
    platform: 'instagram',
    format: 'reel',
    publishedAt: '2026-06-30',
    views: 184200,
    likes: 18200,
    comments: 1340,
    shares: 3420,
    author: 'Riya Sharma',
    state: 'Uttar Pradesh',
    page: 'SAMARTH National Desk',
    theme: 'positive',
    createdAt: '2026-06-30T09:12:00.000Z',
    createdByEmail: 'riya.sharma@varaheanalytics.com'
  },
  {
    id: 'sample-002',
    title: 'Youth employment carousel',
    platform: 'facebook',
    format: 'carousel',
    publishedAt: '2026-06-29',
    views: 92300,
    likes: 7600,
    comments: 842,
    shares: 2180,
    author: 'Arjun Mehta',
    state: 'National',
    page: 'Youth Connect India',
    theme: 'positive',
    createdAt: '2026-06-29T13:32:00.000Z',
    createdByEmail: 'arjun.mehta@varaheanalytics.com'
  },
  {
    id: 'sample-003',
    title: 'Opposition claim fact-check short',
    platform: 'youtube',
    format: 'short',
    publishedAt: '2026-06-29',
    views: 312400,
    likes: 28100,
    comments: 4920,
    shares: 9100,
    author: 'Kabir Rao',
    state: 'National',
    page: 'Bharat Narrative Lab',
    theme: 'negative',
    createdAt: '2026-06-29T15:44:00.000Z',
    createdByEmail: 'kabir.rao@varaheanalytics.com'
  },
  {
    id: 'sample-004',
    title: 'Women safety scheme field story',
    platform: 'instagram',
    format: 'reel',
    publishedAt: '2026-06-28',
    views: 142900,
    likes: 15120,
    comments: 990,
    shares: 2760,
    author: 'Neha Verma',
    state: 'Uttarakhand',
    page: 'Policy Pulse',
    theme: 'positive',
    createdAt: '2026-06-28T10:20:00.000Z',
    createdByEmail: 'neha.verma@varaheanalytics.com'
  },
  {
    id: 'sample-005',
    title: 'Road repair before-after post',
    platform: 'facebook',
    format: 'post',
    publishedAt: '2026-06-27',
    views: 68400,
    likes: 4300,
    comments: 520,
    shares: 1260,
    author: 'Dev Singh',
    state: 'Punjab',
    page: 'Jan Samvad Live',
    theme: 'positive',
    createdAt: '2026-06-27T08:50:00.000Z',
    createdByEmail: 'dev.singh@varaheanalytics.com'
  },
  {
    id: 'sample-006',
    title: 'Power cut grievance narrative',
    platform: 'instagram',
    format: 'reel',
    publishedAt: '2026-06-26',
    views: 77600,
    likes: 6100,
    comments: 1210,
    shares: 1870,
    author: 'Sana Khan',
    state: 'West Bengal',
    page: 'SAMARTH National Desk',
    theme: 'negative',
    createdAt: '2026-06-26T12:10:00.000Z',
    createdByEmail: 'sana.khan@varaheanalytics.com'
  },
  {
    id: 'sample-007',
    title: 'Tourism weekend push',
    platform: 'youtube',
    format: 'video',
    publishedAt: '2026-06-25',
    views: 128700,
    likes: 9100,
    comments: 870,
    shares: 2210,
    author: 'Riya Sharma',
    state: 'Goa',
    page: 'Bharat Narrative Lab',
    theme: 'positive',
    createdAt: '2026-06-25T16:05:00.000Z',
    createdByEmail: 'riya.sharma@varaheanalytics.com'
  },
  {
    id: 'sample-008',
    title: 'Health camp turnout infographic',
    platform: 'facebook',
    format: 'infographic',
    publishedAt: '2026-06-24',
    views: 54800,
    likes: 3900,
    comments: 410,
    shares: 980,
    author: 'Neha Verma',
    state: 'Kerala',
    page: 'Policy Pulse',
    theme: 'positive',
    createdAt: '2026-06-24T10:30:00.000Z',
    createdByEmail: 'neha.verma@varaheanalytics.com'
  },
  {
    id: 'sample-009',
    title: 'Campus voter awareness reel',
    platform: 'instagram',
    format: 'reel',
    publishedAt: '2026-06-23',
    views: 201300,
    likes: 22400,
    comments: 1780,
    shares: 4920,
    author: 'Arjun Mehta',
    state: 'National',
    page: 'Youth Connect India',
    theme: 'positive',
    createdAt: '2026-06-23T18:04:00.000Z',
    createdByEmail: 'arjun.mehta@varaheanalytics.com'
  },
  {
    id: 'sample-010',
    title: 'Local corruption allegation tracker',
    platform: 'youtube',
    format: 'short',
    publishedAt: '2026-06-22',
    views: 176500,
    likes: 12300,
    comments: 3120,
    shares: 5050,
    author: 'Kabir Rao',
    state: 'Uttar Pradesh',
    page: 'UP Development Watch',
    theme: 'negative',
    createdAt: '2026-06-22T14:18:00.000Z',
    createdByEmail: 'kabir.rao@varaheanalytics.com'
  },
  {
    id: 'sample-011',
    title: 'Farmer support scheme FAQ',
    platform: 'facebook',
    format: 'carousel',
    publishedAt: '2026-06-21',
    views: 81500,
    likes: 7100,
    comments: 760,
    shares: 1900,
    author: 'Dev Singh',
    state: 'Punjab',
    page: 'Jan Samvad Live',
    theme: 'positive',
    createdAt: '2026-06-21T09:45:00.000Z',
    createdByEmail: 'dev.singh@varaheanalytics.com'
  },
  {
    id: 'sample-012',
    title: 'Flood response update',
    platform: 'instagram',
    format: 'post',
    publishedAt: '2026-06-20',
    views: 60700,
    likes: 4800,
    comments: 1180,
    shares: 2020,
    author: 'Sana Khan',
    state: 'Kerala',
    page: 'Policy Pulse',
    theme: 'positive',
    createdAt: '2026-06-20T11:15:00.000Z',
    createdByEmail: 'sana.khan@varaheanalytics.com'
  },
  {
    id: 'sample-013',
    title: 'Waterlogging complaint monitor',
    platform: 'facebook',
    format: 'post',
    publishedAt: '2026-06-19',
    views: 39600,
    likes: 2100,
    comments: 940,
    shares: 720,
    author: 'Kabir Rao',
    state: 'West Bengal',
    page: 'SAMARTH National Desk',
    theme: 'negative',
    createdAt: '2026-06-19T09:20:00.000Z',
    createdByEmail: 'kabir.rao@varaheanalytics.com'
  },
  {
    id: 'sample-014',
    title: 'Public transport ridership chart',
    platform: 'youtube',
    format: 'video',
    publishedAt: '2026-06-18',
    views: 96400,
    likes: 7200,
    comments: 640,
    shares: 1680,
    author: 'Riya Sharma',
    state: 'Uttar Pradesh',
    page: 'UP Development Watch',
    theme: 'positive',
    createdAt: '2026-06-18T15:00:00.000Z',
    createdByEmail: 'riya.sharma@varaheanalytics.com'
  },
  {
    id: 'sample-015',
    title: 'Exam paper leak response timeline',
    platform: 'instagram',
    format: 'carousel',
    publishedAt: '2026-06-17',
    views: 118300,
    likes: 9800,
    comments: 2310,
    shares: 3800,
    author: 'Arjun Mehta',
    state: 'National',
    page: 'Youth Connect India',
    theme: 'negative',
    createdAt: '2026-06-17T17:25:00.000Z',
    createdByEmail: 'arjun.mehta@varaheanalytics.com'
  },
  {
    id: 'sample-016',
    title: 'Coastal cleanup volunteer story',
    platform: 'youtube',
    format: 'short',
    publishedAt: '2026-06-16',
    views: 88900,
    likes: 8200,
    comments: 530,
    shares: 1440,
    author: 'Neha Verma',
    state: 'Goa',
    page: 'Bharat Narrative Lab',
    theme: 'positive',
    createdAt: '2026-06-16T13:00:00.000Z',
    createdByEmail: 'neha.verma@varaheanalytics.com'
  },
  {
    id: 'sample-017',
    title: 'Archived duplicate upload sample',
    platform: 'facebook',
    format: 'post',
    publishedAt: '2026-06-14',
    views: 12600,
    likes: 640,
    comments: 120,
    shares: 210,
    author: 'Dev Singh',
    state: 'Punjab',
    page: 'Jan Samvad Live',
    theme: 'positive',
    archivedAt: '2026-06-30T11:00:00.000Z',
    archiveReason: 'duplicate',
    archivedByEmail: 'avipshu.chowdhury@varaheanalytics.com',
    createdAt: '2026-06-14T09:00:00.000Z',
    createdByEmail: 'dev.singh@varaheanalytics.com'
  }
];
